### ISSUE TITLE
Append fails on assertion

### ISSUE THREAD

**Issue by AndreyNevolin** [cemeyer/hadoofus#36]
Hi Conrad,

I'm trying to append to HDFS object, but the operation fails here (highlevel.c:130):

```
    ASSERT(object->ob_type == htype || \
        (object->ob_type == H_NULL && object->ob_val._null._type == htype ) || \
        object->ob_type == H_PROTOCOL_EXCEPTION); \
```

It turns out that "object->ob_type" is "_H_START" in my particular execution.

I'm using Isilon as HDFS backend.

What could be the issue here? Does it look as backend bug?

Backtrace is the following:
![screenshot-2016- -12-759-pm](https://cloud.githubusercontent.com/assets/7734325/17628738/898ba3e4-60bf-11e6-8821-0895fbc7b999.png)

**Comment by cemeyer** [comment]
Hi Andrey,

`_H_START` is the same value as `H_VOID`.  The method is `append()` and currently hadoofus expects it to return a `Locatedblock` object.  But the backend is returning `void`.

That could suggest I've gotten the prototype wrong for the method on the hadoofus side, or that there are multiple different variants of this function.

What version of HDFS is the backend speaking?  1.x, 2.0.x, 2.2.x, newer?

**Comment by cemeyer** [comment]
It seems like in newer versions of HDFS (e.g., 2.7.1), `append()` method returns `LastBlockWithStatus`.  But I don't see a version where it returns `void`.  More information about the protocol version would help :-).

**Comment by cemeyer** [comment]
It looks like Isilon HDFS will return `void` for "v4" Namenode protocol clients.  That means HDFS 1.x, I think.  I'm not sure why — you should ask them :-).  As a workaround, you could use HDFS 2.0 protocol instead:

```
hdfs_namenode_init(&n, ...);
hdfs_namenode_set_version(&n, HDFS_NN_v2);
hdfs_namenode_connect(...);
```

**Comment by AndreyNevolin** [comment]
Conrad,
Thank you very much! You are very responsive as always.

Yeah, I noticed that Hadoofus expects `Locatedblock`. It appeared very suspicious to me that the server returned `void`. But I decided to reach you first because it might be that I got something wrong.

I'll ask HDFS guys what was the reason for `void`.

You guessed protocol version right. It's 1.x. I'll try to switch to 2.x as you suggested. Nothing should change in interacting with Hadoofus, right? From application's perspective everything remains same, right?

**Comment by cemeyer** [comment]
> I'll ask HDFS guys what was the reason for void.

IIRC, it's because Cloudera or some other early 1.x-derived Hadoop distribution used `append` in such a way.  But Cloudera does not publish their cdh3 sources anymore.

> You guessed protocol version right. It's 1.x. I'll try to switch to 2.x as you suggested. Nothing should change in interacting with Hadoofus, right? From application's perspective everything remains same, right?

I think it's pretty much the same, yes.  The same methods are called through the same C functions, except `getProtocolVersion()`, which has been removed.  Most RPCs should return the same type as in HDFS1, although I wouldn't be surprised if they changed a few.

**Comment by AndreyNevolin** [comment]
> IIRC, it's because Cloudera or some other early 1.x-derived Hadoop distribution used  `append`  in such a way

Cool. Funny that Cloudera diverged with the _canonical_ HDFS implementation in such a non-fundamental way. A little bit less funny that Isilon decided to diverge with _canonical_ HDFS in favor of Cloudera. Maybe that's because 'append' is not an operation of great importance when talking about HDFS. Though I know even a couple of projects that implement log-structured file system on top of HDFS.

> I think it's pretty much the same, yes. The same methods are called through the same C functions, except  `getProtocolVersion() `, which has been removed. Most RPCs should return the same type as in HDFS1, although I wouldn't be surprised if they changed a few.

Ok. Thanks. I'll check. How are users expected to check protocol version in HDFS 2?

**Comment by cemeyer** [comment]
I think it may have been because Cloudera was basically the only HDFS-1.x distribution where `append` actually worked.  But I could be mistaken; this is vague memory of hearsay.

> How are users expected to check protocol version in HDFS 2?

I'm not really sure.  You could always try the RPC and catch the resulting exception, but that isn't a great answer.  These URLs are relevant, I think:

* https://issues.apache.org/jira/browse/HADOOP-7994
* http://svn.apache.org/viewvc?view=revision&revision=1236444

Specifically it looks like there is now a `getProtocolSignature()` method?  But I've never heard of that and neither hadoofus nor Isilon HDFS support it.

**Comment by AndreyNevolin** [comment]
Thank you!
